d=read.table(file.choose(),header=T,sep = ";")
png(file="plot4.png",width = 480,height = 480)
par(mfrow=c(2,2),mar=c(3,4,2,2))
plot.default(d$Global_active_power,type = "l",xaxt='n',xlab = " ",ylab = "Global Active Power(kilowatts)",cex.lab=1)
axis(1,at=seq(0,2880,by=1440),labels = c("Thr","Fri","Sat"),cex.axis=1)
plot.default(d$Voltage,ylab = "Voltage",xaxt='n',type = 'l',xlab="datetime", cex.lab=1)
axis(1,at=seq(0,2880,by=1440),labels = c("Thr","Fri","Sat"),cex.axis=1)
with(d,plot.default(Sub_metering_1,type='l',xaxt='n',xlab = " ",ylab = "Energy sub metering"))
with(d,lines(d$Sub_metering_2,col="red"))
with(d,lines(d$Sub_metering_3,col="blue"))
axis(1,at=seq(0,2880,by=1440),labels = c("Thr","Fri","Sat"))
legend("topright",col = c("black","red","blue"),lty=1,
       legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex= 0.7)
plot.default(d$Global_reactive_power,ylab = "Global_reactive_power",xaxt='n',type = 'l',xlab = "datetime", cex.lab=1,cex.axis=1)
axis(1,at=seq(0,2880,by=1440),labels = c("Thr","Fri","Sat"))
dev.off()
